import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Project, Role, Status, User, Country, ExpenseType, Category } from '../types';
import { SUBSIDIARIES, INITIAL_PLANNING_ROW, INITIAL_FINANCE_SCHEDULE } from '../constants';
import { generateAuditLogs } from '../services/auditService';
import { generateUUID } from '../utils';

interface AppContextType {
  currentUser: User;
  switchUser: (userId: string) => void;
  users: User[];
  addUser: (user: User) => void;
  updateUser: (user: User) => void;
  deleteUser: (userId: string) => void;
  projects: Project[];
  getProject: (id: string) => Project | undefined;
  saveProject: (project: Project) => void;
  deleteProject: (id: string) => void;
  updateStatus: (projectId: string, newStatus: Status) => void;
  addComment: (projectId: string, text: string, parentId?: string) => void;
  generateProjectCode: (country: Country, year: string) => string;
  theme: 'light' | 'dark';
  toggleTheme: () => void;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

// Initial Users matching the requirements
const INITIAL_USERS: User[] = [
  { id: 'u1', name: 'John Doe', role: Role.ProjectLead, country: Country.BR },
  { id: 'u2', name: 'Carlos Silva', role: Role.ProjectLead, country: Country.BR },
  { id: 'u3', name: 'Elena Rodriguez', role: Role.CountryManager, country: Country.BR },
  { id: 'u4', name: 'Ahmed Mansour', role: Role.ProjectLead, country: Country.GQ },
  { id: 'u5', name: 'Sarah Conner', role: Role.CountryManager, country: Country.GQ },
  { id: 'u6', name: 'Jean-Luc Picard', role: Role.ProjectLead, country: Country.CG },
  { id: 'u7', name: 'Ellen Ripley', role: Role.CountryManager, country: Country.CG },
  { id: 'u8', name: 'James T. Kirk', role: Role.CEO, country: Country.BR }, // CEO country doesn't restrict view
  { id: 'u9', name: 'Admin User', role: Role.Admin, country: Country.BR },
];

// Initial Dummy Data
const INITIAL_PROJECTS: Project[] = [
  {
    id: '1',
    budgetYear: 2025,
    country: Country.BR,
    code: 'BR-2025-TEdB-001',
    name: 'Pampo Platform Upgrade',
    startDate: '2025-01-15',
    endDate: '2025-11-30',
    concession: 'Pampo – Bicudo',
    category: Category.Maintenance,
    priority: 1,
    owner: 'Carlos Silva',
    reviewers: ['John Doe', 'Elena Rodriguez'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.CAPEX,
    description: 'Structural reinforcement of the main deck.',
    justification: 'Safety critical maintenance required by regulation.',
    planEngineering: { ...INITIAL_PLANNING_ROW, prior: true, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q3: true, q4: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: 'AFE-9921',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 500, q2: 1200, q3: 800 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '2',
    budgetYear: 2025,
    country: Country.GQ,
    code: 'GQ-2025-TEGI-001',
    name: 'Zafiro Well Intervention',
    startDate: '2025-03-01',
    endDate: '2025-06-30',
    concession: 'Block B', 
    category: Category.WellServices,
    priority: 2,
    owner: 'Ahmed Mansour',
    reviewers: ['John Doe'],
    additionalReserves: true,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Routine intervention for well Z-12 to restore production levels.',
    justification: 'Well production has declined by 15% over the last quarter.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 200, q2: 1500 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Submitted,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '3',
    budgetYear: 2025,
    country: Country.CG,
    code: 'CG-2025-TEC-001',
    name: 'Nkossa Digital Twin Pilot',
    startDate: '2025-02-01',
    endDate: '2026-06-01',
    concession: 'Nkossa',
    category: Category.SpecialProjects,
    priority: 3,
    owner: 'Jean-Luc Picard',
    reviewers: ['Sarah Conner', 'Elena Rodriguez'],
    additionalReserves: false,
    multiYear: 'Multi',
    expenseType: ExpenseType.MIX,
    description: 'Implementation of a digital twin for the Nkossa floating production unit.',
    justification: 'Optimization of maintenance schedules and reduction of POB.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q4: true, subsequent: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: 'AFE-NK-002',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 150, q2: 300, q3: 300, q4: 400, y1: 1200 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.CMApproved,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '4',
    budgetYear: 2025,
    country: Country.BR,
    code: 'BR-2025-TEdB-002',
    name: 'Marimba Subsea Tie-back',
    startDate: '2025-02-10',
    endDate: '2025-12-20',
    concession: 'Marimba – Pirauna',
    category: Category.SubseaProjects,
    priority: 1,
    owner: 'Carlos Silva',
    reviewers: ['John Doe'],
    additionalReserves: true,
    multiYear: 'Multi',
    expenseType: ExpenseType.CAPEX,
    description: 'Connection of new subsea wells to the Marimba platform to increase production capacity.',
    justification: 'Maximize recovery from the field reservoir extension.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q3: true, q4: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: 'AFE-MAR-005',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 2000, q2: 4000, q3: 3000, q4: 1000, y1: 5000 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '5',
    budgetYear: 2025,
    country: Country.BR,
    code: 'BR-2025-TEdB-003',
    name: 'Badejo Water Treatment Upgrade',
    startDate: '2025-01-05',
    endDate: '2025-09-30',
    concession: 'Badejo – Linguado',
    category: Category.TopsideProject,
    priority: 2,
    owner: 'John Doe',
    reviewers: ['Elena Rodriguez'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.CAPEX,
    description: 'Upgrading the produced water treatment system to meet new environmental regulations.',
    justification: 'Compliance with new CONAMA resolution.',
    planEngineering: { ...INITIAL_PLANNING_ROW, prior: true, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    initiatedBefore: true,
    prevBudgetRef: 'BR-24-055',
    afeNavRef: 'AFE-BAD-102',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, prior: 200, current: 0, q1: 500, q2: 800, q3: 1200 },
    prevTotalCost: 2700,
    prevExpenditures: 200,
    prevComments: 'Engineering started in late 2024.',
    status: Status.Submitted,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '6',
    budgetYear: 2025,
    country: Country.BR,
    code: 'BR-2025-TEdB-004',
    name: 'Enchova Crane Replacement',
    startDate: '2025-04-01',
    endDate: '2025-10-15',
    concession: 'Bonito – Enchova – Enchova Oeste – Trilha',
    category: Category.Maintenance,
    priority: 1,
    owner: 'Carlos Silva',
    reviewers: ['Elena Rodriguez', 'James T. Kirk'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Replacement of the main deck crane due to end of design life.',
    justification: 'Safety critical for platform logistics.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: 'AFE-ENC-991',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q2: 1500, q3: 1500 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.CMApproved,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '7',
    budgetYear: 2025,
    country: Country.GQ,
    code: 'GQ-2025-TEGI-002',
    name: 'Okume Complex Electrification',
    startDate: '2025-01-20',
    endDate: '2025-07-30',
    concession: 'Okume',
    category: Category.Studies,
    priority: 3,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner'],
    additionalReserves: false,
    multiYear: 'Multi',
    expenseType: ExpenseType.OPEX,
    description: 'Feasibility study and initial implementation for electrifying the Okume complex to reduce diesel consumption.',
    justification: 'Carbon footprint reduction initiative.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW },
    planExecution: { ...INITIAL_PLANNING_ROW },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 300, q2: 200, y1: 15000 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '8',
    budgetYear: 2025,
    country: Country.GQ,
    code: 'GQ-2025-TEGI-003',
    name: 'Ceiba FPSO Hull Inspection',
    startDate: '2025-02-15',
    endDate: '2025-05-15',
    concession: 'Ceiba',
    category: Category.Integrity,
    priority: 1,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Comprehensive diver-less hull inspection campaign for the Ceiba FPSO.',
    justification: 'Class requirement for 5-year certification.',
    planEngineering: { ...INITIAL_PLANNING_ROW, prior: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: 'AFE-CEI-003',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 400, q2: 400 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Submitted,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '9',
    budgetYear: 2025,
    country: Country.GQ,
    code: 'GQ-2025-TEGI-004',
    name: 'Block G Exploration Drilling',
    startDate: '2025-06-01',
    endDate: '2025-12-01',
    concession: 'Block G',
    category: Category.Drilling,
    priority: 2,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner', 'James T. Kirk'],
    additionalReserves: true,
    multiYear: 'Single',
    expenseType: ExpenseType.CAPEX,
    description: 'Drilling of one exploration well in Block G to test new stratigraphic trap concepts.',
    justification: 'Potential to unlock 50M bbl reserves.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q3: true, q4: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: 'AFE-EXP-25-01',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q3: 5000, q4: 4000 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.CEOApproved,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '10',
    budgetYear: 2025,
    country: Country.CG,
    code: 'CG-2025-TEC-002',
    name: 'Moho Nord Phase 3 Study',
    startDate: '2025-01-10',
    endDate: '2025-09-30',
    concession: 'Moho Likouf (non-op)',
    category: Category.Studies,
    priority: 2,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: true,
    multiYear: 'Multi',
    expenseType: ExpenseType.OPEX,
    description: 'Pre-FEED studies for the phase 3 development of Moho Nord.',
    justification: 'Partner requirement to evaluate expansion.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true, q3: true },
    planProcurement: { ...INITIAL_PLANNING_ROW },
    planExecution: { ...INITIAL_PLANNING_ROW },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 600, q2: 600, q3: 600, y1: 20000 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '11',
    budgetYear: 2025,
    country: Country.CG,
    code: 'CG-2025-TEC-003',
    name: 'Djeno Terminal Tank Rehab',
    startDate: '2025-03-01',
    endDate: '2025-10-30',
    concession: 'Nkossa', 
    category: Category.Maintenance,
    priority: 1,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Rehabilitation of crude oil storage tank T-102 at Djeno terminal.',
    justification: 'Tank integrity compromise risk.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true, q4: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: 'AFE-DJE-102',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q2: 1200, q3: 1800 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Revision,
    comments: [
        {
          id: 'c-11-1',
          author: 'Ellen Ripley',
          role: Role.CountryManager,
          text: 'Please review the cost estimate for Q3, it seems high compared to previous tank rehabs.',
          timestamp: new Date(Date.now() - 86400000).toISOString()
        }
    ],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '12',
    budgetYear: 2025,
    country: Country.CG,
    code: 'CG-2025-TEC-004',
    name: 'Lianzi Multiphase Pump Repair',
    startDate: '2025-01-05',
    endDate: '2025-04-01',
    concession: 'Lianzi',
    category: Category.WellServices,
    priority: 1,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Emergency repair and overhaul of the subsea multiphase pump module.',
    justification: 'Pump failure resulting in 3000 bopd deferment.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q1: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: 'AFE-LIA-900',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 2500 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.CMApproved,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- 2026 BR Projects ---
  {
    id: '13',
    budgetYear: 2026,
    country: Country.BR,
    code: 'BR-2026-TEdB-001',
    name: 'Pampo 2026 Major Shutdown',
    startDate: '2026-05-01',
    endDate: '2026-06-15',
    concession: 'Pampo – Bicudo',
    category: Category.Maintenance,
    priority: 1,
    owner: 'Carlos Silva',
    reviewers: ['John Doe'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.CAPEX,
    description: 'Planned statutory shutdown for pressure vessel inspection and safety valve recertification.',
    justification: 'Regulatory requirement NR-13.',
    planEngineering: { ...INITIAL_PLANNING_ROW, prior: true, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 500, q2: 3500 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '14',
    budgetYear: 2026,
    country: Country.BR,
    code: 'BR-2026-TEdB-002',
    name: 'Badejo Digitalization Initiative',
    startDate: '2026-02-01',
    endDate: '2026-11-30',
    concession: 'Badejo – Linguado',
    category: Category.SpecialProjects,
    priority: 3,
    owner: 'John Doe',
    reviewers: ['Elena Rodriguez'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Implementation of wireless sensors for real-time vibration monitoring on rotating equipment.',
    justification: 'Reduce unplanned downtime by 15%.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q3: true, q4: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q2: 200, q3: 300, q4: 100 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Submitted,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '15',
    budgetYear: 2026,
    country: Country.BR,
    code: 'BR-2026-TEdB-003',
    name: 'Enchova Water Injection Upgrade',
    startDate: '2026-03-15',
    endDate: '2026-09-15',
    concession: 'Bonito – Enchova – Enchova Oeste – Trilha',
    category: Category.WellServices,
    priority: 2,
    owner: 'Carlos Silva',
    reviewers: ['Elena Rodriguez'],
    additionalReserves: true,
    multiYear: 'Single',
    expenseType: ExpenseType.CAPEX,
    description: 'Upgrade of water injection pumps to increase reservoir pressure support.',
    justification: 'Expected production increase of 1200 bopd.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q2: 1800, q3: 1200 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- 2026 GQ Projects ---
  {
    id: '16',
    budgetYear: 2026,
    country: Country.GQ,
    code: 'GQ-2026-TEGI-001',
    name: 'Zafiro Subsea Tie-in Z-15',
    startDate: '2026-01-10',
    endDate: '2026-08-30',
    concession: 'Block B',
    category: Category.SubseaProjects,
    priority: 1,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner'],
    additionalReserves: true,
    multiYear: 'Single',
    expenseType: ExpenseType.CAPEX,
    description: 'Tie-in of new infill well Z-15 to the existing subsea manifold.',
    justification: 'Monetization of new reserves.',
    planEngineering: { ...INITIAL_PLANNING_ROW, prior: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q3: true },
    initiatedBefore: true,
    prevBudgetRef: 'GQ-25-ENG-001',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, prior: 300, q1: 1500, q2: 2500, q3: 1000 },
    prevTotalCost: 300,
    prevExpenditures: 300,
    prevComments: 'Engineering completed in 2025.',
    status: Status.CMApproved,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '17',
    budgetYear: 2026,
    country: Country.GQ,
    code: 'GQ-2026-TEGI-002',
    name: 'Ceiba FPSO Life Extension Study',
    startDate: '2026-02-01',
    endDate: '2026-05-30',
    concession: 'Ceiba',
    category: Category.Studies,
    priority: 2,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Detailed fatigue analysis and hull integrity study for 5-year life extension.',
    justification: 'Required for field life extension beyond 2030.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW },
    planExecution: { ...INITIAL_PLANNING_ROW },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 400, q2: 400 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '18',
    budgetYear: 2026,
    country: Country.GQ,
    code: 'GQ-2026-TEGI-003',
    name: 'Okume Logistics Optimization',
    startDate: '2026-04-01',
    endDate: '2026-10-30',
    concession: 'Okume',
    category: Category.Other,
    priority: 3,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Consultancy and implementation of a new marine logistics sharing model.',
    justification: 'Potential OPEX saving of 2M USD/year.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q3: true, q4: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q2: 150, q3: 300, q4: 150 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Submitted,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- 2026 CG Projects ---
  {
    id: '19',
    budgetYear: 2026,
    country: Country.CG,
    code: 'CG-2026-TEC-001',
    name: 'Nkossa Compressor Overhaul',
    startDate: '2026-03-01',
    endDate: '2026-07-15',
    concession: 'Nkossa',
    category: Category.Maintenance,
    priority: 1,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Major overhaul of gas injection compressor K-201.',
    justification: 'Reaching 40,000 running hours, manufacturer recommended.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 800, q2: 2000, q3: 1200 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '20',
    budgetYear: 2026,
    country: Country.CG,
    code: 'CG-2026-TEC-002',
    name: 'Moho Nord Phase 4 Pre-FEED',
    startDate: '2026-01-01',
    endDate: '2026-12-30',
    concession: 'Moho Likouf (non-op)',
    category: Category.Studies,
    priority: 2,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: true,
    multiYear: 'Multi',
    expenseType: ExpenseType.CAPEX,
    description: 'Pre-FEED studies for the next phase of development.',
    justification: 'Long term strategic development.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true, q3: true, q4: true },
    planProcurement: { ...INITIAL_PLANNING_ROW },
    planExecution: { ...INITIAL_PLANNING_ROW },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 500, q2: 500, q3: 500, q4: 500, y1: 15000 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '21',
    budgetYear: 2026,
    country: Country.CG,
    code: 'CG-2026-TEC-003',
    name: 'Djeno Export Line Inspection',
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    concession: 'Nkossa',
    category: Category.Integrity,
    priority: 1,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Intelligent pigging of the 24" export pipeline to Djeno.',
    justification: 'Legal requirement for pipeline integrity management.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q2: 800, q3: 400 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Submitted,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- NEW ADDITIONAL 2026 PROJECTS ---
  {
    id: '22',
    budgetYear: 2026,
    country: Country.GQ,
    code: 'GQ-2026-TEGI-004',
    name: 'Alen Gas Monetization Study',
    startDate: '2026-02-01',
    endDate: '2026-08-01',
    concession: 'Block G',
    category: Category.Studies,
    priority: 2,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner'],
    additionalReserves: true,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Economic modelling and feasibility for new gas monetization routes.',
    justification: 'Strategic planning.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW },
    planExecution: { ...INITIAL_PLANNING_ROW },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 150, q2: 250 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '23',
    budgetYear: 2026,
    country: Country.GQ,
    code: 'GQ-2026-TEGI-005',
    name: 'Zafiro Producer Z-19 Workover',
    startDate: '2026-06-15',
    endDate: '2026-07-30',
    concession: 'Block B',
    category: Category.WellServices,
    priority: 1,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner'],
    additionalReserves: true,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Workover to replace failed ESP pump.',
    justification: 'Restore 1500 bopd production.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q2: 800, q3: 1200 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Submitted,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '24',
    budgetYear: 2026,
    country: Country.GQ,
    code: 'GQ-2026-TEGI-006',
    name: 'Insular Region Logistics Base',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    concession: 'General',
    category: Category.Other,
    priority: 3,
    owner: 'Ahmed Mansour',
    reviewers: ['Sarah Conner'],
    additionalReserves: false,
    multiYear: 'Multi',
    expenseType: ExpenseType.CAPEX,
    description: 'Expansion of the Malabo logistics base to support regional operations.',
    justification: 'Infrastructure upgrade.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true, q4: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 500, q2: 1500, q3: 1500, q4: 1000, y1: 2000 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '25',
    budgetYear: 2026,
    country: Country.CG,
    code: 'CG-2026-TEC-004',
    name: 'Yombo FSO Hull Verification',
    startDate: '2026-03-01',
    endDate: '2026-05-01',
    concession: 'Lianzi',
    category: Category.Integrity,
    priority: 1,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.OPEX,
    description: 'Class survey for hull thickness verification.',
    justification: 'Regulatory compliance.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 200, q2: 300 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '26',
    budgetYear: 2026,
    country: Country.CG,
    code: 'CG-2026-TEC-005',
    name: 'Sendji Gas Lift Optimization',
    startDate: '2026-04-01',
    endDate: '2026-10-01',
    concession: 'Nkossa',
    category: Category.WellServices,
    priority: 2,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: true,
    multiYear: 'Single',
    expenseType: ExpenseType.CAPEX,
    description: 'Installation of new gas lift mandrels in 3 wells.',
    justification: 'Production enhancement.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true, q3: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q2: 1200, q3: 800 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Submitted,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '27',
    budgetYear: 2026,
    country: Country.CG,
    code: 'CG-2026-TEC-006',
    name: 'Pointe Noire Office Solar Panel',
    startDate: '2026-01-15',
    endDate: '2026-06-15',
    concession: 'General',
    category: Category.Other,
    priority: 3,
    owner: 'Jean-Luc Picard',
    reviewers: ['Ellen Ripley'],
    additionalReserves: false,
    multiYear: 'Single',
    expenseType: ExpenseType.CAPEX,
    description: 'Installation of solar panels on the main office roof.',
    justification: 'Green initiative / Carbon reduction.',
    planEngineering: { ...INITIAL_PLANNING_ROW, q1: true },
    planProcurement: { ...INITIAL_PLANNING_ROW, q1: true, q2: true },
    planExecution: { ...INITIAL_PLANNING_ROW, q2: true },
    initiatedBefore: false,
    prevBudgetRef: '',
    afeNavRef: '',
    expenditures: { ...INITIAL_FINANCE_SCHEDULE, q1: 100, q2: 400 },
    prevTotalCost: 0,
    prevExpenditures: 0,
    prevComments: '',
    status: Status.Draft,
    comments: [],
    auditTrail: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const AppProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [users, setUsers] = useState<User[]>(INITIAL_USERS);
  const [currentUser, setCurrentUser] = useState<User>(INITIAL_USERS[0]);
  const [projects, setProjects] = useState<Project[]>(INITIAL_PROJECTS);
  
  // Theme Management
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    if (typeof window !== 'undefined' && window.localStorage) {
        const stored = localStorage.getItem('theme');
        if (stored === 'light' || stored === 'dark') return stored;
        if (window.matchMedia('(prefers-color-scheme: dark)').matches) return 'dark';
    }
    return 'light';
  });

  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove('light', 'dark');
    root.classList.add(theme);
    localStorage.setItem('theme', theme);
  }, [theme]);

  const toggleTheme = () => setTheme(prev => prev === 'light' ? 'dark' : 'light');

  // User Management
  const switchUser = (userId: string) => {
    const user = users.find(u => u.id === userId);
    if (user) setCurrentUser(user);
  };

  const addUser = (user: User) => {
    setUsers(prev => [...prev, user]);
  };

  const updateUser = (updatedUser: User) => {
    setUsers(prev => prev.map(u => u.id === updatedUser.id ? updatedUser : u));
    if (currentUser.id === updatedUser.id) setCurrentUser(updatedUser);
  };

  const deleteUser = (userId: string) => {
    setUsers(prev => prev.filter(u => u.id !== userId));
  };

  const getProject = (id: string) => projects.find(p => p.id === id);

  const generateProjectCode = (country: Country, yearStr: string) => {
    const year = yearStr ? yearStr.substring(0, 4) : new Date().getFullYear().toString();
    const subsidiary = SUBSIDIARIES[country];
    
    // Find count of existing projects for this country/year to increment sequence
    const count = projects.filter(p => p.code.startsWith(`${country}-${year}-${subsidiary}`)).length;
    const sequence = (count + 1).toString().padStart(3, '0');
    
    return `${country}-${year}-${subsidiary}-${sequence}`;
  };

  const saveProject = (projectToSave: Project) => {
    setProjects(prev => {
      const exists = prev.find(p => p.id === projectToSave.id);
      
      // Audit Log Generation
      const logs = generateAuditLogs(exists || null, projectToSave, currentUser.name);
      
      const updatedProject = {
        ...projectToSave,
        auditTrail: [...(exists?.auditTrail || []), ...logs],
        updatedAt: new Date().toISOString()
      };

      if (exists) {
        return prev.map(p => p.id === projectToSave.id ? updatedProject : p);
      }
      return [...prev, updatedProject];
    });
  };

  const deleteProject = (id: string) => {
    setProjects(prev => prev.filter(p => p.id !== id));
  };

  const updateStatus = (projectId: string, newStatus: Status) => {
    const project = getProject(projectId);
    if (!project) return;

    const updatedProject = { ...project, status: newStatus };
    saveProject(updatedProject);
    console.log(`Notification: Project ${project.code} moved to ${newStatus}`);
  };

  const addComment = (projectId: string, text: string, parentId?: string) => {
    setProjects(prev => prev.map(p => {
      if (p.id === projectId) {
        const newComment = {
          id: generateUUID(),
          author: currentUser.name,
          role: currentUser.role,
          text,
          timestamp: new Date().toISOString(),
          parentId
        };
        return { ...p, comments: [...p.comments, newComment] };
      }
      return p;
    }));
  };

  return (
    <AppContext.Provider value={{
      currentUser,
      switchUser,
      users,
      addUser,
      updateUser,
      deleteUser,
      projects,
      getProject,
      saveProject,
      deleteProject,
      updateStatus,
      addComment,
      generateProjectCode,
      theme,
      toggleTheme
    }}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) throw new Error('useApp must be used within AppProvider');
  return context;
};